@template.layout(
title="CS 3220 Examples",
content = @`
    <p>Topic covered:</p>
    <ul>
        <li><a href="https://mynotes.cysun.org/files/view/1001246">Bootstrap</a></li>
        <li>
            <a href="https://mynotes.cysun.org/files/view/1002526">Spring Boot Web MVC (1)</a>
            <a href="https://mynotes.cysun.org/files/view/1002550">(2)</a>
            <a href="https://mynotes.cysun.org/files/view/1002565">(3)</a>
        </li>
        <li><a href="https://mynotes.cysun.org/files/view/1003450">Java Template Engine (JTE)</a></li>
        <li>
            <a href="https://mynotes.cysun.org/files/view/1003068">Spring Data JPA (1)</a>
            <a href="https://mynotes.cysun.org/files/view/1002648">(2)</a>
            <a href="https://mynotes.cysun.org/files/view/1003091">(3)</a>
        </li>
        <li><a href="https://mynotes.cysun.org/files/view/1002677">REST Web API</a></li>
    </ul>
    <p>The source code is available on <a href="https://github.com/cysun/cs3220-examples">GitHub</a>.</p>
`)
